language: ruby
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet

env:
  global:
    - LIBRARIAN_PUPPET_TMP="$HOME/librarian-puppet"
matrix:
  include:
    - rvm: 2.1.9
      env: PUPPET_VERSION="~> 4.5"
    - rvm: 2.3.1
      env: PUPPET_VERSION="~> 4.5"

before_install:
  - gem update bundler

script:
  - bundle exec rake test
